name: flutter_custom_timeline
description: Flutter custom timeline- Customise it on your own way
version: 0.0.6
repository: https://github.com/Shadil-rayeen/Flutter-Custom-Timeline

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timeline_tile: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

